### ISSUE TITLE
btoa in not undefined on server render

### ISSUE THREAD

**Issue by chin2km** [patrickhousley/ngx-axios-adapter#10]
Issue:
This lib used `btoa` for authentication headers but btoa is not supported on node.js. The wwhole pupose of this lib is to make ssr possible and somehow its interner using something server doesnt support?

**Comment by patrickhousley** [comment]
Thanks for reporting the issue. I had no idea that was a problem since my tests pass. Let me dig in a little and feel free to offer up a pull request.
