### ISSUE TITLE
Incorrect peer dependencies warnings

### ISSUE THREAD

**Issue by villeharjunen** [patrickhousley/ngx-axios-adapter#9]
I'm getting following warnings after updating to version 1.0.2
```
warning " > @ngx-axios-adapter/core@1.0.2" has incorrect peer dependency "@angular/common@^6.0.0-rc.0 || ^6.0.0".
warning " > @ngx-axios-adapter/core@1.0.2" has incorrect peer dependency "@angular/core@^6.0.0-rc.0 || ^6.0.0".
warning " > @ngx-axios-adapter/core@1.0.2" has unmet peer dependency "@angular/http@^6.0.0-rc.0 || ^6.0.0".
warning " > @ngx-axios-adapter/core@1.0.2" has incorrect peer dependency "axios@^0.18.0".
```
I think `peerDependencies` in `libs/core/package.json` should also be updated to support angular ^8.0.0. and axios ^0.19.0.

**Comment by patrickhousley** [comment]
Sorry about that. Can you try 1.0.3?

**Comment by villeharjunen** [comment]
Updated to 1.03. and all good but got:
```
warning " > @ngx-axios-adapter/core@1.0.3" has unmet peer dependency "@angular/http@^8.0.0-rc.0 || ^8.0.0".
```
I looked at the code and I couldn't find any imports from `@angular/http` only `@angular/common/http`. It seems that `@angular/http` could be removed from the peer dependencies.

**Comment by patrickhousley** [comment]
Thanks again @villeharjunen I have pushed 1.0.4

**Comment by villeharjunen** [comment]
Updated and all good now.
